# Generated by Django 5.0.7 on 2024-09-05 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoicebill_app', '0003_employee_delete_customer_delete_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='lasttname',
            new_name='lastname',
        ),
    ]
