# Generated by Django 5.0.7 on 2024-09-05 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicebill_app', '0004_rename_lasttname_employee_lastname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
